# Bite workbox interactive shell configuration

export EDITOR="${EDITOR:-nvim}"
export VISUAL="$EDITOR"

HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000

setopt append_history
setopt hist_ignore_dups
setopt share_history

autoload -Uz compinit
compinit

alias ll='ls -la'
alias glog='git log --oneline --graph --decorate -10'
alias b='bun'
alias bi='bun install'
alias br='bun run'
alias bd='bun dev'
alias bx='bunx'
alias reload='source ~/.zshrc'

PROMPT='%F{cyan}%n@%m%f:%F{blue}%~%f %# '
